extends SceneTree
const Pose = preload("res://net/pose.gd")
const Playback = preload("res://media/playback.gd")
func _initialize() -> void:
	var poses: Array[Transform3D] = [Transform3D(Basis(Vector3.UP, 0.7), Vector3(1,2,3)), Transform3D.IDENTITY, Transform3D.IDENTITY]
	var encoded := Pose.encode(42, poses, 3)
	var decoded := Pose.decode(encoded)
	assert(decoded.sequence == 42 and decoded.tracked == 3)
	assert(decoded.poses[0].is_equal_approx(poses[0]))
	encoded.encode_float(32, NAN)
	assert(Pose.decode(encoded).is_empty())
	assert(Pose.decode(PackedByteArray([0,1])).is_empty())
	assert(Playback.target_position({"position":10.0,"stamp":50.0,"paused":false}, 53.0) == 13.0)
	assert(Playback.target_position({"position":10.0,"stamp":50.0,"paused":true}, 53.0) == 10.0)
	assert(not Playback.valid_snapshot({"position":NAN}))
	assert(encoded.size() == Pose.LENGTH and Pose.LENGTH <= 1100)
	assert(Pose.newer(0, 0xffffffff) and not Pose.newer(0xffffffff, 0))
	assert(not Pose.newer(42, 42))
	var joints: Array[Quaternion] = []
	for i in range(30): joints.append(Quaternion(Vector3(1,2,3).normalized(), float(i) / 30))
	var curls := PackedFloat32Array([0,0.2,0.4,0.6,1,1,0.6,0.4,0.2,0])
	encoded = Pose.encode(0xffffffff,poses,7,joints,PackedInt32Array([32767,16383]),curls,12,9)
	decoded = Pose.decode(encoded)
	assert(decoded.epoch == 12 and decoded.reset_epoch == 9 and decoded.masks[1] == 16383)
	for i in range(30): assert(absf(decoded.fingers[i].dot(joints[i])) > 0.99999)
	for i in range(10): assert(is_equal_approx(decoded.curls[i], curls[i]))
	var malformed := encoded.duplicate()
	malformed.encode_u32(24,65535)
	assert(Pose.decode(malformed).is_empty())
	malformed = encoded.duplicate()
	malformed.encode_float(116,INF)
	assert(Pose.decode(malformed).is_empty())
	malformed = encoded.duplicate()
	malformed.encode_float(596,-1)
	assert(Pose.decode(malformed).is_empty())
	var catalog = preload("res://avatars/catalog.gd")
	assert(catalog.valid_state(JSON.parse_string('{"avatar":"alicia","revision":1,"eye_height":1.6,"epoch":12}')))
	assert(not catalog.valid_state({"avatar":"alicia","revision":1,"eye_height":NAN,"epoch":0}))
	assert(not catalog.valid_state({"avatar":"alicia","revision":1,"eye_height":1.6,"epoch":0.5}))
	print("PROTOCOL_TESTS_PASSED")
	quit()
